### PR TITLE
feature(Design) : Redesign landing page

### PR DESCRIPTION
**Pull request by rovilay**
#### What does this PR do?
* Redesign Landing Page
#### Description of Task to be completed?
* Create mock-up of proposed designs
* Convert approved designs to HTML and CSS
* Implement the new design
#### How should this be manually tested?
* N/A
#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker stories?
* #159501217
#### Screenshots or gifs (if appropriate)
screen shot 2018-08-10 at 5 20 16 pm

#### Questions:
* N/A

### CODE REVIEW

**Comment by phemonick** [comment]
The heroku deployment doesnt contain the latest changes

**Comment by otseobande** [comment]
screen shot 2018-08-11 at 6 08 10 am

The cards are still transparent in this area.

**Review by nouwatinjacob — APPROVED** [review]
Nice work. Keep it up

**Review by phemonick — APPROVED** [review]
Nice Job, keep it up.

**Pull request merged**
